require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'vender/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/**/*'
  TargetRubyVersion: 3.2
  SuggestExtensions: false

Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
RSpec/ChangeByZero:
  Enabled: false
